# Étape 1: Construction de l'application
FROM maven:3.9.8-openjdk-17 AS build
WORKDIR /app

# Copie des fichiers Maven pour la mise en cache des dépendances
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copie du reste de l'application
COPY src /app/src
RUN mvn package -DskipTests

# Étape 2: Image exécutable allégée
FROM openjdk:17-jdk-slim
WORKDIR /app

# Copier l'application depuis l'étape de build
COPY --from=build /app/target/*.jar app.jar

# Exposer le port sur lequel l'application écoute
EXPOSE 8070s

# Lancer l'application
ENTRYPOINT ["java", "-jar", "app.jar"]
