apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pg
  namespace: lcf-k8s-devops
spec:
  storageClassName: "hostpath"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi