server:
  port: 8090
spring:
  data:
    mongodb:
      username: tall
      password: tall
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

#server:
#  port: 8090
#spring:
#  data:
#    mongodb:
#      uri: mongodb://admin:pass@localhost:27010/customer?authSource=admin&serverTimezone=UTC
#
#server:
#  port: 8090
